/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maria' at '10/03/16 11:44' with Gradle 2.11
 *
 * @author maria, @date 10/03/16 11:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
